# Generated by Django 5.0 on 2024-01-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infinitrax', '0004_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
