# Generated by Django 5.0 on 2024-01-02 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Infinitrax', '0005_alter_inventory_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='attribute',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Infinitrax.product', to_field='serialno'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='taxrate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
